// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Shabandinho",
            "email": "mahmoudshaband@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "get All Categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "get All Categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/output.Category"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add New Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Add New Category",
                "parameters": [
                    {
                        "description": "category data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/output.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/categories/{category_id}": {
            "patch": {
                "description": "Update  Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Update  Category",
                "parameters": [
                    {
                        "description": "category data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryDTO"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "category id",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "delete": {
                "description": "delete  Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "delete  Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clients": {
            "get": {
                "description": "get All Clients",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "get All Clients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/output.Client"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add New Client",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Add New Client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enter client name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "enter client email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "enter client phone",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": " is client ?",
                        "name": "is_client",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "is supplier ?",
                        "name": "is_supplier",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/output.Client"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/clients/{client_id}": {
            "patch": {
                "description": "Update  Client",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Update  Client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enter client name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "enter client email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "enter client phone",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "is client ?",
                        "name": "is_client",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "is supplier ?",
                        "name": "is_supplier",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "client id",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Client"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "delete": {
                "description": "delete  Client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "delete  Client",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inventories": {
            "get": {
                "description": "get All Inventories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventories"
                ],
                "summary": "get All Inventories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/output.Inventory"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add New Inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventories"
                ],
                "summary": "Add New Inventory",
                "parameters": [
                    {
                        "description": "inventory data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InventoryDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/output.Inventory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/inventories/{id}": {
            "delete": {
                "description": "delete  Inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventories"
                ],
                "summary": "delete  Inventory",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inventory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inventories/{inventory_id}": {
            "patch": {
                "description": "Update  Inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventories"
                ],
                "summary": "Update  Inventory",
                "parameters": [
                    {
                        "description": "inventory data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InventoryDTO"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "inventory id",
                        "name": "inventory_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Inventory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/invoices": {
            "get": {
                "description": "get All Invoices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoices"
                ],
                "summary": "get All Invoices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/output.Invoice"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add New Invoice",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoices"
                ],
                "summary": "Add New Invoice",
                "parameters": [
                    {
                        "description": "invoice data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InvoiceDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Invoice Stored Successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "get All Products",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "get All Products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/output.Product"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add New Product",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Add New Product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enter product name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "enter product code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "enter product cost price",
                        "name": "cost_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "enter product sell price",
                        "name": "sell_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "category ID",
                        "name": "category_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "image",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/output.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "delete": {
                "description": "delete  Product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "delete  Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/products/{product_id}": {
            "get": {
                "description": "show  Product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "show  Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update  Product",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update  Product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "enter product name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "enter product code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "enter product cost price",
                        "name": "cost_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "enter product sell price",
                        "name": "sell_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "category ID",
                        "name": "category_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "get All Users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "get All Users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/output.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add New User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Add New User",
                "parameters": [
                    {
                        "description": "user data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/output.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "delete": {
                "description": "delete  User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "delete  User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "patch": {
                "description": "Update  User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update  User",
                "parameters": [
                    {
                        "description": "user data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserDTO"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/output.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CategoryDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "category1"
                }
            }
        },
        "dto.CreateUserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "shaband@shaband.com"
                },
                "name": {
                    "type": "string",
                    "example": "shaband"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                },
                "password_confirmation": {
                    "type": "string",
                    "example": "123"
                },
                "phone": {
                    "type": "string",
                    "example": "0123456789"
                }
            }
        },
        "dto.InventoryDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "address1"
                },
                "name": {
                    "type": "string",
                    "example": "inventory1"
                }
            }
        },
        "dto.InvoiceDTO": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "integer",
                    "example": 1
                },
                "inventory_id": {
                    "type": "integer",
                    "example": 6
                },
                "is_sell": {
                    "type": "boolean",
                    "example": true
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.InvoiceItemDTO"
                    }
                },
                "total_cost": {
                    "type": "number",
                    "example": 1000
                },
                "total_price": {
                    "type": "number",
                    "example": 10000
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.InvoiceItemDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1
                },
                "product_id": {
                    "type": "integer",
                    "example": 1
                },
                "unit_cost_price": {
                    "type": "number",
                    "example": 1000
                },
                "unit_sell_price": {
                    "type": "number",
                    "example": 10000
                }
            }
        },
        "dto.UpdateUserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "shaband@shaband.com"
                },
                "name": {
                    "type": "string",
                    "example": "shaband"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                },
                "password_confirmation": {
                    "type": "string",
                    "example": "123"
                },
                "phone": {
                    "type": "string",
                    "example": "0123456789"
                }
            }
        },
        "model.Category": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "category1"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Product"
                    }
                }
            }
        },
        "model.Client": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_client": {
                    "type": "boolean"
                },
                "is_supplier": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Inventory": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "address1"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "category1"
                },
                "productStock": {
                    "$ref": "#/definitions/model.InventoryToProduct"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Product"
                    }
                }
            }
        },
        "model.InventoryToProduct": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "buy_invoices_count": {
                    "type": "integer"
                },
                "inventory": {
                    "$ref": "#/definitions/model.Inventory"
                },
                "inventoryID": {
                    "type": "integer"
                },
                "product": {
                    "$ref": "#/definitions/model.Product"
                },
                "productID": {
                    "type": "integer"
                },
                "sell_invoices_count": {
                    "type": "integer"
                }
            }
        },
        "model.Product": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/model.Category"
                },
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "code": {
                    "type": "string",
                    "example": "123"
                },
                "cost_price": {
                    "type": "string",
                    "example": "10"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string",
                    "example": "http://lorempicsm/100.jpg"
                },
                "inventories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Inventory"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "category1"
                },
                "sell_price": {
                    "type": "string",
                    "example": "100"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "output.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "category1"
                }
            }
        },
        "output.Client": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "shaband@shaband.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "isClient": {
                    "type": "boolean",
                    "example": true
                },
                "isSupplier": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "shaband"
                },
                "phone": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "output.HTTPError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "name field is required"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "output.Inventory": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "address1"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "inventory"
                }
            }
        },
        "output.Invoice": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/output.NameWithID"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "inventory": {
                    "$ref": "#/definitions/output.NameWithID"
                },
                "isSell": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.InvoiceItem"
                    }
                },
                "totalCost": {
                    "type": "number"
                },
                "totalPrice": {
                    "type": "number"
                },
                "user": {
                    "$ref": "#/definitions/output.NameWithID"
                }
            }
        },
        "output.InvoiceItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 3
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "product": {
                    "$ref": "#/definitions/output.Product"
                },
                "totalCost": {
                    "type": "number",
                    "example": 6
                },
                "totalPrice": {
                    "type": "number",
                    "example": 3
                },
                "unitCostPrice": {
                    "type": "number",
                    "example": 2
                },
                "unitSellPrice": {
                    "type": "number",
                    "example": 1
                }
            }
        },
        "output.NameWithID": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "name"
                }
            }
        },
        "output.Product": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "124"
                },
                "cost_price": {
                    "type": "string",
                    "example": "5"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string",
                    "example": "http://image.com/image.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "product 1"
                },
                "sell_price": {
                    "type": "string",
                    "example": "10"
                }
            }
        },
        "output.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "shaband@shaband.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "shaband"
                },
                "phone": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3500",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "POS API",
	Description:      "This is a POS api docs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
