basePath: /api/v1
definitions:
  dto.CategoryDTO:
    properties:
      name:
        example: category1
        type: string
    type: object
  model.Category:
    properties:
      category_id:
        example: 1
        type: integer
      id:
        example: 1
        type: integer
      name:
        example: category1
        type: string
    type: object
  output.Category:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: category1
        type: string
    type: object
  output.HTTPError:
    properties:
      message:
        example: name field is required
        type: string
      success:
        example: false
        type: boolean
    type: object
host: localhost:3500
info:
  contact:
    email: mahmoudshaband@gmail.com
    name: Shabandinho
  description: This is a POS api docs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: POS API
  version: "1.0"
paths:
  /categories:
    get:
      consumes:
      - application/json
      description: get All Categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/output.Category'
            type: array
      summary: get All Categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Add New Category
      parameters:
      - description: category data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CategoryDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/output.Category'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/output.HTTPError'
      summary: Add New Category
      tags:
      - categories
  /categories/{category_id}:
    patch:
      consumes:
      - application/json
      description: Update New Category
      parameters:
      - description: category data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CategoryDTO'
      - description: category id
        in: path
        name: category_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/output.HTTPError'
      summary: Update New Category
      tags:
      - categories
  /categories/{id}:
    delete:
      consumes:
      - application/json
      description: delete  Category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: deleted successfully
          schema:
            type: string
      summary: delete  Category
      tags:
      - categories
swagger: "2.0"
